name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-anon-usage
  - archspec
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - blosc
  - boltons
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - conda
  - conda-content-trust
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cryptography
  - cycler
  - distro
  - expat
  - fiona
  - fmt
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - frozendict
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - giflib
  - h2
  - hdf4
  - hdf5
  - hpack
  - hyperframe
  - icu
  - idna
  - jinja2
  - joblib
  - json-c
  - jsonpatch
  - jsonpointer
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libkml
  - liblapack
  - libmamba
  - libmambapy
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libsolv
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libunistring
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - menuinst
  - minizip
  - munkres
  - ncurses
  - networkx
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pixman
  - platformdirs
  - pluggy
  - poppler
  - poppler-data
  - postgresql
  - proj
  - pthread-stubs
  - pybind11-abi
  - pycountry
  - pycosat
  - pycparser
  - pyogrio
  - pyopenssl
  - pyparsing
  - pyproj
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python.app
  - python_abi
  - pytz
  - qhull
  - rasterio
  - re2
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snappy
  - spdlog
  - sqlite
  - swig
  - threadpoolctl
  - tiledb
  - tk
  - tornado
  - tqdm
  - truststore
  - tzcode
  - tzdata
  - uriparser
  - urllib3
  - wheel
  - xlsxwriter
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml-cpp
  - zlib
  - zstandard
  - zstd
  - wget
  - pip:
      - affine
      - confusables
      - munch
      - rasterio
      - snuggs
      - wget
      - workbook
      - pyreadstat
      - pycountry
      - openpyxl
      - xlsxwriter
      - workbook
      - unidecode
